"""
Primary UAST-DL configuration — aligned with Table 1 of the paper.

ResNet101 + DeepLabv3+ + EMA Mean Teacher + UST(τ=0.95) + Warm-up(5) + Tversky/Dice/CE
"""

EXPERIMENT_NAME = "UAST_DL_Primary"
ENABLE_K_FOLD = True
NUM_FOLDS = 5
ENABLE_WANDB = False
SEED = 42

TRAIN_BATCH_SIZE = 2
VAL_BATCH_SIZE = 1
NUM_EPOCHS = 200
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 1e-4

ENABLE_EARLY_STOPPING = True
EARLY_STOPPING_PATIENCE = 30
EARLY_STOPPING_MONITOR = "val_miou"

NUM_CLASSES = 2
MODEL_ARCHITECTURE = "deeplabv3plus"
IMAGE_SIZE = (512, 512)
ENCODER_NAME = "resnet101"
ENCODER_WEIGHTS = "imagenet"
ENCODER_OUTPUT_STRIDE = 16

TEACHER_MODE = "ema"
EMA_DECAY = 0.999
CONFIDENCE_THRESHOLD = 0.95
UST_MASK_MODE = "class_balance"
UST_BG_WEIGHT = 0.1
WARMUP_EPOCHS = 5
UNSUP_RAMPUP_EPOCHS = 5
UNSUPERVISED_WEIGHT = 1.0
TPRAM_ENABLED = False

CE_WEIGHT = 0.5
TVERSKY_WEIGHT = 1.0
DICE_WEIGHT = 1.0
ENABLE_TVERSKY = True
TVERSKY_ALPHA = 0.3
TVERSKY_BETA = 0.7
DICE_CLASS_WEIGHTS = [1.0, 10.0]

OPTIMIZER = "sgd"
LR_SCHEDULER = "poly"
POWER = 0.9

USE_SLIDING_WINDOW_EVAL = True
SLIDING_WINDOW_SIZE = (512, 512)
SLIDING_WINDOW_STRIDE = (256, 256)

MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]
LOG_INTERVAL = 10
